spring.application.name=chat-app-backend

spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/chatapp}

frontend.url=${FRONTEND_URL:http://localhost:5173}

#one problem its always disconnect the user once they do nothing for heartbeat time.. need to chech the exact reason what making it stop like opning new window or keeping it still freze configure it
